logging:
  level:
    org.springframework.cloud.task: debug

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://116.126.158.6:3306/dataflowTest?useUnicode=true&characterEncoding=UTF8&useSSL=false
#    url: jdbc:mariadb://116.126.158.6:3306/dataflow?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: lawshop
    password: znzn2753@

  application:
    name: Bill-Setup-Task
