logging:
  level:
    org.springframework.cloud.task: debug

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dataflow?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: rootpw

  application:
    name: Bill Run

  batch:
    jdbc:
      initialize-schema: always
