logging:
  level:
    org.springframework.cloud.task: debug

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/dataflow?serverTimezone=UTC&characterEncoding=UTF-8

    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://116.126.158.6:3306/dataflow?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: rootpw

  application:
    name: Bill Run

  batch:
    jdbc:
      initialize-schema: always

  sql:
    init:
      mode: always
